[build]
  command = "yarn build"
  publish = "build/"
[[plugins]]
  package = "netlify-plugin-clacks"
[[plugins]]
  package = "netlify-plugin-inline-source"
[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://social.effy.space/.well-known/webfinger"
[[redirects]]
  from = "/.well-known/nodeinfo"
  to = "https://social.effy.space/.well-known/nodeinfo"
[[redirects]]
  from = "/.well-known/host-meta"
  to = "https://social.effy.space/.well-known/host-meta"
[[redirects]]
  from = "/api/*"
  to = "https://social.effy.space/api/:splat"
