[build]
  command = "yarn build"
  publish = "build/"
[[plugins]]
  package = "netlify-plugin-clacks"
[[plugins]]
  package = "netlify-plugin-inline-source"
[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://social.effy.space/.well-known/webfinger"